#!/usr/bin/env bash

mkdir -p ~/.config/run

if [[ -d ~/.bashrc.d ]]; then
  tee ~/.bashrc.d/50-tmux-workwlow-alias <<EOF
alias wf='tmux -S ~/.config/run/tmux attach -d -t $USER-workwlow 2>/dev/null || tmux -S ~/.config/run/tmux new -t $USER-workwlow'
EOF
fi
